import { useEffect, useId, useRef, useState } from 'react';
import { mermaidThemeVariables } from '@shared/mermaid-block';
import { appPaletteForId } from '@shared/terminal-theme';
import { useStore } from '../store';

/**
 * One ```mermaid fence, rendered as a diagram.
 *
 * mermaid is imported lazily and cached module-wide: it is by far the largest
 * dependency in the renderer, and most previewed notes contain no diagram, so
 * the chunk must not land in the initial bundle. The first diagram in a session
 * pays the load; later ones reuse the resolved promise.
 *
 * On the raw-HTML rule in MarkdownView: mermaid emits an SVG string, and the
 * only way to mount it is a DOM write. That is safe in a way pasted note HTML
 * would not be — the markup is generated by mermaid from the diagram grammar
 * (not copied out of the note), and `securityLevel: 'strict'` runs mermaid's
 * DOMPurify pass over it. The write goes through a ref into a container React
 * treats as empty, so React never adopts the subtree either. Under the app CSP
 * (`script-src 'self'`) any script mermaid failed to strip would not execute;
 * the inline `<style>` mermaid does emit is covered by `style-src 'unsafe-inline'`.
 *
 * Errors are contained: a diagram that fails to parse falls back to the source
 * text plus the message, so a typo in one fence never blanks the note.
 */

type MermaidApi = typeof import('mermaid').default;

let mermaidPromise: Promise<MermaidApi> | null = null;

function loadMermaid(): Promise<MermaidApi> {
  mermaidPromise ??= import('mermaid').then((m) => m.default);
  return mermaidPromise;
}

export function MermaidBlock({ code }: { code: string }) {
  const themeId = useStore((s) => s.settings.terminalTheme);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [rendered, setRendered] = useState(false);

  // useId's value contains colons, which are not valid in the CSS selectors
  // mermaid builds from the id it is handed.
  const reactId = useId();
  const id = `mermaid-${reactId.replace(/[^a-zA-Z0-9_-]/g, '')}`;

  useEffect(() => {
    let cancelled = false;
    setError(null);

    void (async () => {
      try {
        const mermaid = await loadMermaid();
        if (cancelled) return;

        // Config is global to mermaid, so re-apply before each render: a theme
        // change has to reach diagrams that mounted under the previous palette.
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: 'strict',
          suppressErrorRendering: true,
          theme: 'base',
          themeVariables: mermaidThemeVariables(appPaletteForId(themeId)),
        });

        const { svg, bindFunctions } = await mermaid.render(id, code);
        if (cancelled) return;
        const el = containerRef.current;
        if (!el) return;
        el.innerHTML = svg;
        bindFunctions?.(el);
        setRendered(true);
      } catch (err) {
        if (cancelled) return;
        if (containerRef.current) containerRef.current.innerHTML = '';
        setRendered(false);
        setError(err instanceof Error ? err.message : String(err));
      } finally {
        // mermaid measures in an offscreen node named after the render id and
        // only tidies it up on the success path — never the rendered `#${id}`
        // svg itself, which by then lives in our container.
        document.getElementById(`d${id}`)?.remove();
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [code, themeId, id]);

  if (error !== null) {
    return (
      <div
        className="my-3 overflow-x-auto rounded border border-treeline-red/50 bg-treeline-highlight/40 p-3"
        data-ss="mermaid-error"
      >
        <div className="mb-2 font-mono text-xs text-treeline-red">Diagram error: {error}</div>
        <pre className="overflow-x-auto font-mono text-xs leading-relaxed text-treeline-dim">
          {code}
        </pre>
      </div>
    );
  }

  return (
    <div
      className="my-3 overflow-x-auto rounded border border-treeline-highlight bg-treeline-highlight/40 p-3 text-center [&_svg]:mx-auto [&_svg]:h-auto [&_svg]:max-w-full"
      data-ss="mermaid"
      data-rendered={rendered ? 'true' : 'false'}
      ref={containerRef}
    />
  );
}
