import { app } from 'electron';
import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

/**
 * Makes the `treeline` CLI usable from a *downloaded* build, which ships only
 * `out/**` + `package.json` — not a source checkout. Two delivery paths:
 *
 *  1. Auto-inject (zero setup): the app writes a `treeline` shim under its
 *     userData dir and prepends that dir to the PATH of every terminal it
 *     spawns (see `pty-manager.ts`), so agents running *inside* treeline can
 *     call `treeline …` with no install step.
 *  2. Global install (opt-in): a menu item symlinks the same shim into
 *     `/usr/local/bin` so terminals *outside* treeline can use it too.
 *
 * The shim runs the bundled client via the app's own Electron binary in Node
 * mode (`ELECTRON_RUN_AS_NODE`), so it needs no system Node on PATH.
 */

/** Conventional location for the global symlink (usually already on PATH). */
export const GLOBAL_CLI_PATH = '/usr/local/bin/treeline';

/**
 * Absolute path to the bundled CLI client script. Packaged builds asar-unpack
 * `bin/**`, so the real file lives next to the asar; in dev it's in the repo.
 */
export function cliScriptPath(): string {
  const appPath = app.getAppPath();
  // When packaged, getAppPath() ends in `app.asar`; asarUnpack places real
  // files in the sibling `app.asar.unpacked`. In dev it's the project root.
  const base = app.isPackaged ? `${appPath}.unpacked` : appPath;
  return join(base, 'bin', 'treeline.mjs');
}

/** Managed bin dir under userData — the dir auto-injected into terminal PATH. */
export function cliBinDir(): string {
  return join(app.getPath('userData'), 'bin');
}

/** Path of the generated `treeline` shim. */
export function cliShimPath(): string {
  return join(cliBinDir(), 'treeline');
}

/** Single-quote a string for safe interpolation into the /bin/sh shim. */
function shellQuote(s: string): string {
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

/**
 * Render the shim script. Pure (no fs/electron) so it can be unit-tested.
 * `TREELINE_CLI_BIN` is exported so the client can self-reference this stable,
 * Node-free entrypoint when wiring Claude Code hooks instead of its own path.
 */
export function renderShim(opts: { execPath: string; scriptPath: string; shimPath: string }): string {
  return [
    '#!/bin/sh',
    '# Auto-generated by treeline-app — do not edit; it is rewritten on launch.',
    "# Runs the bundled CLI via the app's own Electron (ELECTRON_RUN_AS_NODE),",
    '# so no system Node is required.',
    `export TREELINE_CLI_BIN=${shellQuote(opts.shimPath)}`,
    `ELECTRON_RUN_AS_NODE=1 exec ${shellQuote(opts.execPath)} ${shellQuote(opts.scriptPath)} "$@"`,
    '',
  ].join('\n');
}

/**
 * Write `contents` to `path` (chmod 0755) only if it differs from what's there.
 * Returns true if it wrote. Skipping unchanged writes keeps the file's mtime
 * stable across launches while still self-healing after an app update moves
 * the Electron binary. Pure fs — unit-testable against a tmp dir.
 */
export function writeExecutableIfChanged(path: string, contents: string): boolean {
  let current: string | null = null;
  try {
    current = readFileSync(path, 'utf8');
  } catch {
    /* absent — will write */
  }
  if (current === contents) return false;
  writeFileSync(path, contents);
  chmodSync(path, 0o755);
  return true;
}

/**
 * Write (idempotently) the `treeline` shim into the managed bin dir.
 * Returns the bin dir so callers can prepend it to spawned-terminal PATHs.
 */
export function materializeCliShim(): string {
  const binDir = cliBinDir();
  mkdirSync(binDir, { recursive: true });
  const shimPath = cliShimPath();
  const contents = renderShim({
    execPath: process.execPath,
    scriptPath: cliScriptPath(),
    shimPath,
  });
  writeExecutableIfChanged(shimPath, contents);
  return binDir;
}

export interface GlobalInstallResult {
  ok: boolean;
  path?: string;
  error?: string;
}

/**
 * Symlink the shim into `/usr/local/bin` so terminals outside treeline can use
 * `treeline`. Never clobbers a real file we didn't create: replaces an existing
 * symlink, but refuses if a regular file is already there. Returns a structured
 * result so the caller can surface a permission error in a dialog.
 */
export function installGlobalCli(): GlobalInstallResult {
  const shim = cliShimPath();
  if (!existsSync(shim)) materializeCliShim();

  try {
    let existing: ReturnType<typeof lstatSync> | null = null;
    try {
      existing = lstatSync(GLOBAL_CLI_PATH);
    } catch {
      /* nothing there — fine */
    }
    if (existing) {
      if (!existing.isSymbolicLink()) {
        return {
          ok: false,
          error: `${GLOBAL_CLI_PATH} already exists and is not a symlink. Remove it and try again.`,
        };
      }
      rmSync(GLOBAL_CLI_PATH, { force: true });
    }
    symlinkSync(shim, GLOBAL_CLI_PATH);
    return { ok: true, path: GLOBAL_CLI_PATH };
  } catch (e) {
    return { ok: false, error: e instanceof Error ? e.message : String(e) };
  }
}
